"""Stamp a validated Git tag into the module PyInstaller freezes."""
from pathlib import Path
import re
import sys


def normalized_version(tag: str) -> str:
    value = (tag or "").strip().lstrip("vV")
    if not re.fullmatch(r"\d+\.\d+\.\d+", value):
        raise ValueError(f"release tag must be vMAJOR.MINOR.PATCH, got {tag!r}")
    return value


def stamp(tag: str, root: Path) -> str:
    version = normalized_version(tag)
    target = root / "bridge" / "_release_version.py"
    target.write_text(
        '"""Generated by packaging/stamp_version.py during release."""\n\n'
        f'__version__ = "{version}"\n',
        encoding="utf-8",
    )
    pyproject = root / "pyproject.toml"
    text = pyproject.read_text(encoding="utf-8")
    text, count = re.subn(
        r'(?m)^version = "[^"]+"$',
        f'version = "{version}"',
        text,
        count=1,
    )
    if count != 1:
        raise ValueError("pyproject.toml must contain exactly one project version")
    pyproject.write_text(text, encoding="utf-8")
    return version


if __name__ == "__main__":
    repository_root = Path(__file__).resolve().parents[1]
    print(stamp(sys.argv[1] if len(sys.argv) > 1 else "", repository_root))
